[package]
name = "codcel-table-engine"
version = "0.1.2"
edition = "2021"
authors = ["Codcel <support@codcel.io>"]
description = "Shared utilities for Codcel table engines including conditions, search traits, and constants."
documentation = "https://codcel.io"
readme = "README.md"
license-file = "LICENSES/LICENSING.md"
repository = "https://github.com/codcel-io/codcel-table-engine"
homepage   = "https://codcel.io"
keywords = ["excel", "finance", "codcel", "spreadsheet", "functions"]
categories = ["mathematics", "finance"]


[dependencies]
codcel-calculation-engine = { git = "https://github.com/codcel-io/codcel-calculation-engine.git", tag = "release-0.1.2" }
async-trait = "0.1.89"
regex = "1.12.3"
once_cell = "1.21.3"
